FROM mcr.microsoft.com/dotnet/sdk:9.0.100-rc.2 AS build

WORKDIR /app

COPY . .

WORKDIR /app/src/kriefTrackAiApi.Web

RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0.0-rc.2 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 6060

ENTRYPOINT ["dotnet", "kriefTrackAiApi.Web.dll"]
