global using FastEndpoints;
global using FastEndpoints.Swagger;
global using MediatR;
global using Serilog;
global using Serilog.Extensions.Logging;
global using Ardalis.Result;
global using HttpGet = Microsoft.AspNetCore.Mvc.HttpGetAttribute;
global using HttpPost = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
global using HttpPut = Microsoft.AspNetCore.Mvc.HttpPutAttribute;
global using HttpDelete = Microsoft.AspNetCore.Mvc.HttpDeleteAttribute;
global using FromBody = Microsoft.AspNetCore.Mvc.FromBodyAttribute;